export const HERO_STATS = [
  { value: "11,000+ MT", label: "Solar structures\nsupplied" },
  { value: "40+ MW", label: "Mandated across\nRajasthan & Jharkhand" },
  { value: "10+ Tier-1", label: "Brands" },
  { value: "Up to 61 Days*", label: "Collateral-free credit\n*T&C apply" },
];

export const SOLAR_FAQ = [
  {
    question: "What do you supply?",
    answer:
      "Panels, inverters, batteries, controllers, lighting, pumps, BOS — single products to complete kits and project bundles.",
  },
  {
    question: "What's in a solar kit?",
    answer:
      "Modules, inverter, DCDB/ACDB, cables, connectors, earthing set, lightning arrester and mounting structure. Ready to install.",
  },
  {
    question: "Are products certified?",
    answer:
      "Yes — matched to IEC, BIS and MNRE standards. Documentation provided on request.",
  },
  {
    question: "Lead time and delivery?",
    answer: "{{Typical range}}. Pan-India delivery, scheduled to your site.",
  },
  {
    question: "Do you offer credit?",
    answer: "Yes — collateral-free, up to 61 days for qualifying projects.*",
  },
  {
    question: "Minimum order?",
    answer: "{{State policy}}.",
  },
];

const DEFAULT_HOW_STEPS = [
  {
    step: 1,
    title: "Add to Cart & Submit Quote",
    desc: "Add items to your cart and request a quote",
  },
  {
    step: 2,
    title: "Get Quote in 24 Hrs",
    desc: "Availability Confirmation & Quote Within a Day",
  },
  {
    step: 3,
    title: "Delivery Options Available",
    desc: "Select delivery to your home or warehouse pickup",
  },
];

const buildDefaultDetails = (skuSize) => [
  { label: "SKU", value: `${skuSize}_BOS_DCR_TOPCON` },
  { label: "Shipping", value: "Free Shipping" },
  { label: "T&C", value: "Non Returnable" },
  { label: "Note", value: "Structure & Installation Charges Not Included" },
  { label: "Type", value: "Ready To Install Solar Kit" },
  { label: "Scheme", value: "PM SURYA GHAR MUFT BIJALI YOJANA" },
  { label: "Subsidy", value: "Eligible for Government Subsidies" },
];

const KIT_1_1_SPEC_ROWS = [
  {
    component: "Solar Panel",
    specifications: "575 Wp N-Type TOPCon Mono Solar Module (22.26% Eff.) ALMM",
    brand: "ALMM",
    qty: 2,
    units: "Nos.",
  },
  {
    component: "Solar MPPT / Inverter",
    specifications: "Solar MPPT (1.1 kW) ALMM",
    brand: "ALMM",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "MC4 Connectors",
    specifications: "M-160 / F-160",
    brand: "NINGBO",
    qty: 2,
    units: "Nos.",
  },
  {
    component: "ACDB To Inverter Cable",
    specifications: "2C x 2.5 Sq.mm Cu. Flexible, 1.1 KVA",
    brand: "POLYCAB",
    qty: 10,
    units: "Mtr.",
  },
  {
    component: "DC Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 10,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 10,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 16 Sqmm AL Flexible",
    brand: "POLYCAB",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "Solar ACDB",
    specifications: "1 IN 1 Out Single Phase",
    brand: "SR Green",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Earthing",
    specifications: "14 mm dia, 1 m long, 10 kg BFC with pit cover",
    brand: "SRG",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "Lighting Arrester",
    specifications: "10 M Radius LA With HRD",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Pipe",
    specifications: "25 mm",
    brand: "AKG",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "PVC Band",
    specifications: "25 mm",
    brand: "AKG",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "Sadel",
    specifications: "25 mm",
    brand: "AKG",
    qty: 20,
    units: "Nos.",
  },
  {
    component: "PVC Tape",
    specifications: "PVC Tape R Y B",
    brand: "Steelgrip",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tray",
    specifications: "25 x 25 MM",
    brand: "CONNECTWELL",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Gitti & Pitch",
    specifications: "38 mm",
    brand: "AKG",
    qty: 60,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tie",
    specifications: "200 mm UV Protected",
    brand: "KS/Tycon",
    qty: 20,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "2.5 mm Ring & Pin Type",
    brand: "Comet",
    qty: 10,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "4 mm Ring & Pin Type",
    brand: "Comet",
    qty: 10,
    units: "Nos.",
  },
  {
    component: "Module Mounting Structure",
    specifications:
      "Solar Mounting Structure, Hot-dip Galvanised with Hot-dip Hardware",
    brand: "SR Green",
    qty: 1.1,
    units: "Kw.",
  },
];

const KIT_2_2_SPEC_ROWS = [
  {
    component: "Solar Panel",
    specifications: "575 Wp N-Type TOPCon Mono Solar Module (22.26% Eff.) ALMM",
    brand: "ALMM",
    qty: 4,
    units: "Nos.",
  },
  {
    component: "Solar Inverter / MPPT",
    specifications: "On-Grid Solar Inverter 2.2 kW",
    brand: "ALMM",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "MC4 Connectors",
    specifications: "M-160 / F-160",
    brand: "NINGBO",
    qty: 4,
    units: "Nos.",
  },
  {
    component: "ACDB To Inverter Cable",
    specifications: "2C x 2.5 Sq.mm Cu. Flexible, 2.2 KVA",
    brand: "POLYCAB",
    qty: 15,
    units: "Mtr.",
  },
  {
    component: "DC Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 15,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 16 Sqmm AL Flexible",
    brand: "POLYCAB",
    qty: 25,
    units: "Mtr.",
  },
  {
    component: "Solar ACDB",
    specifications: "1 IN 1 Out Single Phase",
    brand: "SR Green",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Earthing",
    specifications: "14 mm dia, 1 m long, 10 kg BFC with pit cover",
    brand: "SRG",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "Lighting Arrester",
    specifications: "10 M Radius LA With HRD",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Pipe",
    specifications: "25 mm",
    brand: "AKG",
    qty: 25,
    units: "Mtr.",
  },
  {
    component: "PVC Band",
    specifications: "25 mm",
    brand: "AKG",
    qty: 5,
    units: "Nos.",
  },
  {
    component: "Sadel",
    specifications: "25 mm",
    brand: "AKG",
    qty: 25,
    units: "Nos.",
  },
  {
    component: "PVC Tape",
    specifications: "PVC Tape R Y B",
    brand: "Steelgrip",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tray",
    specifications: "25 x 25 MM",
    brand: "CONNECTWELL",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Gitti & Pitch",
    specifications: "38 mm",
    brand: "AKG",
    qty: 80,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tie",
    specifications: "200 mm UV Protected",
    brand: "KS/Tycon",
    qty: 25,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "2.5 mm Ring & Pin Type",
    brand: "Comet",
    qty: 12,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "4 mm Ring & Pin Type",
    brand: "Comet",
    qty: 12,
    units: "Nos.",
  },
  {
    component: "Module Mounting Structure",
    specifications:
      "Solar Mounting Structure, Hot-dip Galvanised with Hot-dip Hardware",
    brand: "SR Green",
    qty: 2.2,
    units: "Kw.",
  },
];

const KIT_3_3_SPEC_ROWS = [
  {
    component: "Solar Panel",
    specifications: "575 Wp N-Type TOPCon Mono Solar Module (22.26% Eff.) ALMM",
    brand: "ALMM",
    qty: 6,
    units: "Nos.",
  },
  {
    component: "Solar Inverter",
    specifications: "On-Grid Solar Inverter 3.3 kW",
    brand: "ALMM",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "MC4 Connectors",
    specifications: "M-160 / F-160",
    brand: "NINGBO",
    qty: 4,
    units: "Nos.",
  },
  {
    component: "ACDB To Customer Panel",
    specifications: "3.5C x 4 Sq.mm AL ARMD Cable 1.1 KVA",
    brand: "POLYCAB",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "DC Cables (modules connect)",
    specifications: "1R x 1C, 4 Sq.mm DC Cables, 0.6/1.5 KV",
    brand: "POLYCAB",
    qty: 50,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 25,
    units: "Mtr.",
  },
  {
    component: "Solar DCDB",
    specifications: "1 IN 1 Out",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Solar ACDB",
    specifications:
      "1 IN 1 Out, MCCB (3P+N) 32A with SPD (MCCB-L&T/C&S, SPD-Phoenix)",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Earthing",
    specifications: "14 mm dia 3 m long 25 kg BFC with pit cover",
    brand: "SRG",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "Lighting Arrester",
    specifications: "10M Radius LA With HRD",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Pipe",
    specifications: "25 mm",
    brand: "AKG",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "PVC Band",
    specifications: "25 mm",
    brand: "AKG",
    qty: 6,
    units: "Nos.",
  },
  {
    component: "Sadel",
    specifications: "25 mm",
    brand: "AKG",
    qty: 20,
    units: "Nos.",
  },
  {
    component: "PVC Tape",
    specifications: "PVC Tape R Y B",
    brand: "STEEL GRIP",
    qty: 2,
    units: "Nos.",
  },
  {
    component: "PVC Gitti & Pitch",
    specifications: "38 mm",
    brand: "AKG",
    qty: 80,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tie",
    specifications: "300 mm UV Protected",
    brand: "KS",
    qty: 20,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tray",
    specifications: "25 x 25 MM",
    brand: "CONNECTWELL",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "4 mm Ring & Pin Type",
    brand: "ACTION",
    qty: 16,
    units: "Nos.",
  },
  {
    component: "Module Mounting Structure",
    specifications:
      "Solar Mounting Structure Hotdip Galvanised with Hot Dip Hardware",
    brand: "SRG",
    qty: 3.3,
    units: "Kw.",
  },
  {
    component: "Installation & Commissioning",
    specifications:
      "Structure, PV Panel, Inverters, ACDBs & LT Panel with all Accessories + Loading & Unloading",
    brand: "SRG",
    qty: 3.3,
    units: "Kw.",
  },
];

const KIT_5_5_SPEC_ROWS = [
  {
    component: "Solar Panel",
    specifications: "575 Wp N-Type TOPCon Mono Solar Module (22.26% Eff.) ALMM",
    brand: "ALMM",
    qty: 10,
    units: "Nos.",
  },
  {
    component: "Solar Inverter",
    specifications: "On-Grid Solar Inverter 5.5 kW",
    brand: "ALMM",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "MC4 Connectors",
    specifications: "M-160 / F-160",
    brand: "NINGBO",
    qty: 4,
    units: "Nos.",
  },
  {
    component: "DC Cables (modules connect)",
    specifications: "1R x 1C, 4 Sq.mm DC Cables, 0.6/1.5 KV",
    brand: "POLYCAB",
    qty: 85,
    units: "Mtr.",
  },
  {
    component: "ACDB To Customer Panel",
    specifications: "3.5C x 4 Sq.mm AL ARMD Cable 1.1 KVA",
    brand: "POLYCAB",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 30,
    units: "Mtr.",
  },
  {
    component: "Solar DCDB",
    specifications: "1 IN 1 Out",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Solar ACDB",
    specifications:
      "1 IN 1 Out, MCCB (3P+N) 32A with SPD (MCCB-L&T/C&S, SPD-Phoenix)",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Earthing",
    specifications: "14 mm dia 3 m long 25 kg BFC with pit cover",
    brand: "SRG",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "Lighting Arrester",
    specifications: "10M Radius LA With HRD",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Pipe",
    specifications: "25 mm",
    brand: "AKG",
    qty: 22,
    units: "Mtr.",
  },
  {
    component: "PVC Band",
    specifications: "25 mm",
    brand: "AKG",
    qty: 7,
    units: "Nos.",
  },
  {
    component: "Sadel",
    specifications: "25 mm",
    brand: "AKG",
    qty: 24,
    units: "Nos.",
  },
  {
    component: "PVC Tape",
    specifications: "PVC Tape R Y B",
    brand: "STEEL GRIP",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "PVC Gitti & Pitch",
    specifications: "38 mm",
    brand: "AKG",
    qty: 110,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tie",
    specifications: "300 mm UV Protected",
    brand: "KS",
    qty: 25,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tray",
    specifications: "25 x 25 MM",
    brand: "CONNECTWELL",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "4 mm Ring & Pin Type",
    brand: "ACTION",
    qty: 22,
    units: "Nos.",
  },
  {
    component: "Module Mounting Structure",
    specifications:
      "Solar Mounting Structure AL. MONO RAIL with SS Hardware",
    brand: "SRG",
    qty: 5.5,
    units: "Kw.",
  },
  {
    component: "Installation & Commissioning",
    specifications:
      "Structure, PV Panel, Inverters, ACDBs & LT Panel with all Accessories + Loading & Unloading",
    brand: "SRG",
    qty: 5.5,
    units: "Kw.",
  },
];

const KIT_10_SPEC_ROWS = [
  {
    component: "Solar Panel",
    specifications: "575 Wp N-Type TOPCon Mono Solar Module (22.26% Eff.) ALMM",
    brand: "ALMM",
    qty: 18,
    units: "Nos.",
  },
  {
    component: "Solar Inverter",
    specifications: "On-Grid Solar Inverter 10 kW",
    brand: "ALMM",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "MC4 Connectors",
    specifications: "M-160 / F-160",
    brand: "NINGBO",
    qty: 4,
    units: "Nos.",
  },
  {
    component: "DC Cables (modules connect)",
    specifications: "1R x 1C, 4 Sq.mm DC Cables, 0.6/1.5 KV",
    brand: "POLYCAB",
    qty: 130,
    units: "Mtr.",
  },
  {
    component: "ACDB To Customer Panel",
    specifications: "3.5C x 6 Sq.mm AL ARMD Cable 1.1 KVA",
    brand: "POLYCAB",
    qty: 20,
    units: "Mtr.",
  },
  {
    component: "Earthing Cable",
    specifications: "1C x 4 Sqmm Cu. Flexible",
    brand: "POLYCAB",
    qty: 30,
    units: "Mtr.",
  },
  {
    component: "Solar DCDB",
    specifications: "1 IN 1 Out",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Solar ACDB",
    specifications:
      "1 IN 1 Out, MCCB (3P+N) 32A with SPD (MCCB-L&T/C&S, SPD-Phoenix)",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "Earthing",
    specifications: "14 mm dia 3 m long 25 kg BFC with pit cover",
    brand: "SRG",
    qty: 3,
    units: "Nos.",
  },
  {
    component: "Lighting Arrester",
    specifications: "10M Radius LA With HRD",
    brand: "SRG",
    qty: 1,
    units: "Nos.",
  },
  {
    component: "PVC Pipe",
    specifications: "25 mm",
    brand: "AKG",
    qty: 30,
    units: "Mtr.",
  },
  {
    component: "PVC Band",
    specifications: "25 mm",
    brand: "AKG",
    qty: 10,
    units: "Nos.",
  },
  {
    component: "Sadel",
    specifications: "25 mm",
    brand: "AKG",
    qty: 40,
    units: "Nos.",
  },
  {
    component: "PVC Tape",
    specifications: "PVC Tape R Y B",
    brand: "STEEL GRIP",
    qty: 4,
    units: "Nos.",
  },
  {
    component: "PVC Gitti & Pitch",
    specifications: "38 mm",
    brand: "AKG",
    qty: 200,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tie",
    specifications: "300 mm UV Protected",
    brand: "KS",
    qty: 50,
    units: "Nos.",
  },
  {
    component: "PVC Cable Tray",
    specifications: "25 x 25 MM",
    brand: "CONNECTWELL",
    qty: 2,
    units: "Nos.",
  },
  {
    component: "Lugs",
    specifications: "4 mm Ring & Pin Type",
    brand: "ACTION",
    qty: 32,
    units: "Nos.",
  },
  {
    component: "Module Mounting Structure",
    specifications:
      "Solar Mounting Structure AL. MONO RAIL with SS Hardware",
    brand: "SRG",
    qty: 10,
    units: "Kw.",
  },
  {
    component: "Installation & Commissioning",
    specifications:
      "Structure, PV Panel, Inverters, ACDBs & LT Panel with all Accessories + Loading & Unloading",
    brand: "SRG",
    qty: 10,
    units: "Kw.",
  },
];

const DEFAULT_SPEC_ROWS = [
  {
    component: "Solar Panel",
    specifications: "575 Wp N-Type TOPCon Mono Solar Module (22.26% Eff.) ALMM",
    brand: "CONNECTWELL",
    qty: 1,
    units: "NOS.",
  },
  {
    component: "Module Mounting Structure",
    specifications: "Solar Mounting Structure, Hot-dip Galvanised with Hot-dip Hardware",
    brand: "CONNECTWELL",
    qty: 1,
    units: "NOS.",
  },
  {
    component: "Module Mounting Structure",
    specifications: "Solar Mounting Structure, Hot-dip Galvanised with Hot-dip Hardware",
    brand: "CONNECTWELL",
    qty: 1,
    units: "NOS.",
  },
  {
    component: "Module Mounting Structure",
    specifications: "Solar Mounting Structure, Hot-dip Galvanised with Hot-dip Hardware",
    brand: "CONNECTWELL",
    qty: 1,
    units: "NOS.",
  },
  {
    component: "Module Mounting Structure",
    specifications: "Solar Mounting Structure, Hot-dip Galvanised with Hot-dip Hardware",
    brand: "CONNECTWELL",
    qty: 1,
    units: "NOS.",
  },
];

export const SOLAR_KITS = [
  {
    slug: "topcon-dcr-1-1-kw",
    power: "1.1 kW",
    title: "TopCon DCR 1.1 kW Kit",
    fullTitle: "Headsup B2B TopCon DCR 1.1 kW Kit",
    desc: "N-Type TOPCon · 575 Wp modules · Ready to install",
    longDescription:
      "A ready-to-install on-grid solar kit built around high-efficiency N-Type TOPCon modules and matched balance-of-system components — engineered for reliable rooftop generation.",
    image: "/solar-kits/kit-1-5.png",
    imgScale: 0.9,
    gallery: [
      "/solar-kits/kit-1-5.png",
      "/solar-kits/kit-1-1.png",
      "/solar-kits/kit-1-2.png",
      "/solar-kits/kit-1.png",
    ],
    highlights: [
      { label: "MODULE POWER", value: "575 Wp" },
      { label: "CELL TYPE", value: "N-Type" },
      { label: "EFFICIENCY", value: "22.26 %" },
      { label: "MODULE TYPE", value: "TOPCon" },
    ],
    features: ["Free Shipping", "Ready To Install Kit", "Subsidy Eligible"],
    details: buildDefaultDetails("1.1kW"),
    howItWorksSteps: DEFAULT_HOW_STEPS,
    specsTable: KIT_1_1_SPEC_ROWS,
  },
  {
    slug: "topcon-dcr-2-2-kw",
    power: "2.2 kW",
    title: "TopCon DCR 2.2 kW Kit",
    fullTitle: "Headsup B2B TopCon DCR 2.2 kW Kit",
    desc: "Single-phase · MPPT inverter · Full BOS",
    longDescription:
      "Single-phase on-grid kit for small rooftops — N-Type TOPCon modules paired with an MPPT inverter and complete balance-of-system components.",
    image: "/solar-kits/kit-1-3.png",
    gallery: [
      "/solar-kits/kit-1-3.png",
      "/solar-kits/kit-1-1.png",
      "/solar-kits/kit-1-2.png",
      "/solar-kits/kit-1-3.png",
    ],
    highlights: [
      { label: "MODULE POWER", value: "575 Wp" },
      { label: "CELL TYPE", value: "N-Type" },
      { label: "EFFICIENCY", value: "22.26 %" },
      { label: "MODULE TYPE", value: "TOPCon" },
    ],
    features: ["Free Shipping", "Ready To Install Kit", "Subsidy Eligible"],
    details: buildDefaultDetails("2.2kW"),
    howItWorksSteps: DEFAULT_HOW_STEPS,
    specsTable: KIT_2_2_SPEC_ROWS,
  },
  {
    slug: "topcon-dcr-3-3-kw",
    power: "3.3 kW",
    title: "TopCon DCR 3.3 kW Kit",
    fullTitle: "Headsup B2B TopCon DCR 3.3 kW Kit",
    desc: "Subsidy-eligible · Mounting + earthing",
    longDescription:
      "Subsidy-eligible 3.3 kW on-grid kit engineered for typical Indian rooftops — modules, inverter, mounting and earthing included.",
    image: "/solar-kits/kit-3-5.png",
    gallery: [
      "/solar-kits/kit-3-5.png",
      "/solar-kits/kit-3-1.png",
      // "/solar-kits/kit-3-2.png",
      "/solar-kits/kit-3-3.png",
      "/solar-kits/kit-3-4.png",
    ],
    highlights: [
      { label: "MODULE POWER", value: "575 Wp" },
      { label: "CELL TYPE", value: "N-Type" },
      { label: "EFFICIENCY", value: "22.26 %" },
      { label: "MODULE TYPE", value: "TOPCon" },
    ],
    features: ["Free Shipping", "Ready To Install Kit", "Subsidy Eligible"],
    details: buildDefaultDetails("3.3kW"),
    howItWorksSteps: DEFAULT_HOW_STEPS,
    specsTable: KIT_3_3_SPEC_ROWS,
  },
  {
    slug: "topcon-dcr-5-5-kw",
    power: "5.5 kW",
    title: "TopCon DCR 5.5 kW Kit",
    fullTitle: "Headsup B2B TopCon DCR 5.5 kW Kit",
    desc: "Three-phase · Project-grade BOS",
    longDescription:
      "Three-phase 5.5 kW kit for commercial rooftops with project-grade BOS and documentation for statutory compliance.",
    image: "/solar-kits/kit-3-6.png",
    gallery: [
      "/solar-kits/kit-3-6.png",
      "/solar-kits/kit-3-1.png",
      // "/solar-kits/kit-3-2.png",
      "/solar-kits/kit-3-3.png",
      "/solar-kits/kit-3-4.png",
    ],
    highlights: [
      { label: "MODULE POWER", value: "575 Wp" },
      { label: "CELL TYPE", value: "N-Type" },
      { label: "EFFICIENCY", value: "22.26 %" },
      { label: "MODULE TYPE", value: "TOPCon" },
    ],
    features: ["Free Shipping", "Ready To Install Kit", "Subsidy Eligible"],
    details: buildDefaultDetails("5.5kW"),
    howItWorksSteps: DEFAULT_HOW_STEPS,
    specsTable: KIT_5_5_SPEC_ROWS,
  },
  {
    slug: "topcon-dcr-9-5-kw",
    power: "9.5 kW",
    title: "TopCon DCR 9.5 kW Kit",
    fullTitle: "Headsup B2B TopCon DCR 9.5 kW Kit",
    desc: "High-yield modules · SLD support included",
    longDescription:
      "9.5 kW kit with high-yield TOPCon modules — SLD and structural support included for faster approvals.",
    image: "/solar-kits/kit-3-5.png",
    gallery: [
      "/solar-kits/kit-3-5.png",
      "/solar-kits/kit-3-1.png",
      // "/solar-kits/kit-3-2.png",
      "/solar-kits/kit-3-3.png",
      "/solar-kits/kit-3-4.png",
    ],
    highlights: [
      { label: "MODULE POWER", value: "575 Wp" },
      { label: "CELL TYPE", value: "N-Type" },
      { label: "EFFICIENCY", value: "22.26 %" },
      { label: "MODULE TYPE", value: "TOPCon" },
    ],
    features: ["Free Shipping", "Ready To Install Kit", "Subsidy Eligible"],
    details: buildDefaultDetails("9.5kW"),
    howItWorksSteps: DEFAULT_HOW_STEPS,
    specsTable: KIT_5_5_SPEC_ROWS,
  },
  {
    slug: "topcon-dcr-10-kw",
    power: "10 kW",
    title: "TopCon DCR 10 kW Kit",
    fullTitle: "Headsup B2B TopCon DCR 10 kW Kit",
    desc: "Custom sizing · Full O&M coverage",
    longDescription:
      "10 kW kit with custom sizing options and full O&M coverage for uninterrupted generation.",
    image: "/solar-kits/kit-3-6.png",
    gallery: [
      "/solar-kits/kit-3-6.png",
      "/solar-kits/kit-3-1.png",
      // "/solar-kits/kit-3-2.png",
      "/solar-kits/kit-3-3.png",
      "/solar-kits/kit-3-4.png",
    ],
    highlights: [
      { label: "MODULE POWER", value: "575 Wp" },
      { label: "CELL TYPE", value: "N-Type" },
      { label: "EFFICIENCY", value: "22.26 %" },
      { label: "MODULE TYPE", value: "TOPCon" },
    ],
    features: ["Free Shipping", "Ready To Install Kit", "Subsidy Eligible"],
    details: buildDefaultDetails("10kW"),
    howItWorksSteps: DEFAULT_HOW_STEPS,
    specsTable: KIT_10_SPEC_ROWS,
  },
];
